"""
Email helper. All outbound mail goes through this.

From:     hello@stratasnap.com.au
Reply-To: grahame.dickson@gmail.com

Uses Resend API. Requires RESEND_API_KEY env var.
"""

import os
import httpx
from typing import Optional


FROM_ADDRESS = "StrataSnap <hello@stratasnap.com.au>"
REPLY_TO = "grahame.dickson@gmail.com"
INTERNAL_INBOX = "grahame.dickson@gmail.com"


def send_email(
    to: str,
    subject: str,
    html: str,
    text: Optional[str] = None,
    reply_to: Optional[str] = None,
) -> bool:
    """Send a single email via Resend. Returns True on success."""
    api_key = os.environ.get("RESEND_API_KEY")
    if not api_key:
        print("[email] RESEND_API_KEY not set — skipping send")
        return False

    payload = {
        "from": FROM_ADDRESS,
        "to": [to] if isinstance(to, str) else to,
        "subject": subject,
        "html": html,
        "reply_to": reply_to or REPLY_TO,
    }
    if text:
        payload["text"] = text

    try:
        r = httpx.post(
            "https://api.resend.com/emails",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json=payload,
            timeout=10,
        )
        if r.status_code >= 400:
            print(f"[email] Resend error {r.status_code}: {r.text}")
            return False
        return True
    except Exception as e:
        print(f"[email] Exception sending: {e}")
        return False


def notify_internal(subject: str, html: str) -> bool:
    """Send an internal notification to grahame.dickson@gmail.com."""
    return send_email(INTERNAL_INBOX, subject, html)


# ────────────────────────────────────────────────────────────
# Email templates
# ────────────────────────────────────────────────────────────

BASE_STYLE = """
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Inter', sans-serif; background: #F4F1EA; margin: 0; padding: 24px; color: #1A1A1A; }
  .container { max-width: 560px; margin: 0 auto; background: #ffffff; border: 1px solid rgba(26,26,26,0.15); padding: 40px; }
  h1 { font-family: 'Fraunces', Georgia, serif; font-weight: 800; font-size: 32px; margin: 0 0 24px; line-height: 1.1; }
  h2 { font-family: 'Fraunces', Georgia, serif; font-weight: 700; font-size: 20px; margin: 32px 0 12px; }
  p { line-height: 1.6; color: rgba(26,26,26,0.85); margin: 0 0 16px; }
  .tag { font-family: 'JetBrains Mono', monospace; font-size: 10px; text-transform: uppercase; letter-spacing: 0.2em; color: #C73E1D; margin-bottom: 16px; }
  .btn { display: inline-block; background: #1A1A1A; color: #F4F1EA; padding: 14px 24px; text-decoration: none; font-weight: 500; margin: 16px 0; }
  .btn:hover { background: #C73E1D; }
  .footer { margin-top: 40px; padding-top: 24px; border-top: 1px solid rgba(26,26,26,0.15); font-size: 11px; color: rgba(26,26,26,0.5); font-family: 'JetBrains Mono', monospace; text-transform: uppercase; letter-spacing: 0.15em; }
  .disclaimer { background: rgba(26,26,26,0.03); border: 1px solid rgba(26,26,26,0.15); padding: 16px; font-size: 12px; line-height: 1.6; margin: 24px 0; }
</style>
"""

FOOTER = """
<div class="footer">
  StrataSnap · Sydney, NSW · A service of Vapour Film Lighting Pty Ltd, trading as StrataSnap
  <br><br>
  Information only. Not legal, financial, or property advice. Always consult a qualified conveyancer before making a property purchase decision.
</div>
"""


def build_html(inner: str) -> str:
    return f"<!DOCTYPE html><html><head><meta charset='utf-8'>{BASE_STYLE}</head><body><div class='container'>{inner}{FOOTER}</div></body></html>"


def email_report_ready(to: str, view_url: str, property_address: Optional[str] = None) -> bool:
    """Send the customer their completed strata summary."""
    subject = f"Your StrataSnap summary is ready" + (f" · {property_address}" if property_address else "")
    inner = f"""
      <div class="tag">Summary ready</div>
      <h1>Your StrataSnap summary.</h1>
      <p>Your strata summary is ready to view. It pulls out the financial position, by-laws, defects, and insurance from your document, with references to the Strata Schemes Management Act 2015 (NSW).</p>
      <a href="{view_url}" class="btn">View your summary →</a>
      <p style="font-size: 13px; color: rgba(26,26,26,0.6);">The link stays active for 30 days. After that we automatically delete your document and summary from our servers.</p>
      <h2>What to do next</h2>
      <p>Take the summary to your conveyancer. The "Items to discuss with your conveyancer" section is a good starting list.</p>
      <div class="disclaimer">
        <strong>Important.</strong> This summary is generated by AI. It is not legal, financial, or property advice. It is not a substitute for review by a qualified conveyancer or solicitor.
      </div>
      <p style="font-size: 13px; color: rgba(26,26,26,0.6);">Spot an error? Reply to this email — we'll review it.</p>
    """
    return send_email(to, subject, build_html(inner))


def email_purchase_confirmation(to: str, tier: str, credits: int, dashboard_url: str) -> bool:
    """Confirm a bundle purchase and give access details."""
    tier_labels = {"single": "Single report", "fivepack": "5-pack", "tenpack": "10-pack"}
    tier_label = tier_labels.get(tier, tier)

    if credits > 1:
        credit_line = f"You now have <strong>{credits} report credits</strong> ready to use. Bundle credits don't expire."
    else:
        credit_line = "You have 1 report credit ready to use."

    subject = f"Payment received · {tier_label}"
    inner = f"""
      <div class="tag">Payment received</div>
      <h1>Thanks.</h1>
      <p>Your {tier_label} purchase is confirmed.</p>
      <p>{credit_line}</p>
      <a href="{dashboard_url}" class="btn">Go to your dashboard →</a>
      <h2>How to use your credits</h2>
      <p>Log in via the magic link on any device. Upload a strata PDF, we generate the summary. One credit deducts per report. No expiry.</p>
      <p style="font-size: 13px; color: rgba(26,26,26,0.6);">Receipt from Stripe will arrive separately.</p>
    """
    return send_email(to, subject, build_html(inner))


def email_magic_link(to: str, link_url: str) -> bool:
    """Send a magic link to log in."""
    subject = "Your StrataSnap login link"
    inner = f"""
      <div class="tag">Login link</div>
      <h1>Log in to StrataSnap.</h1>
      <p>Click the link below to access your dashboard. It expires in 15 minutes and can only be used once.</p>
      <a href="{link_url}" class="btn">Log in →</a>
      <p style="font-size: 13px; color: rgba(26,26,26,0.6);">Didn't request this? You can safely ignore this email. Nothing will happen.</p>
    """
    return send_email(to, subject, build_html(inner))


def email_lead_notification(lead_type: str, record: dict) -> bool:
    """Notify grahame@gmail about a new conveyancer/buyers-agent lead."""
    label = "Conveyancer" if lead_type == "conveyancer" else "Buyers' Agent"
    subject = f"New {label} lead: {record.get('firm_name', 'unknown')}"
    inner = f"""
      <h1>New {label} lead</h1>
      <p><strong>Firm:</strong> {record.get('firm_name', '—')}</p>
      <p><strong>Contact:</strong> {record.get('contact_name', '—')}</p>
      <p><strong>Email:</strong> <a href="mailto:{record.get('contact_email', '')}">{record.get('contact_email', '—')}</a></p>
      <p><strong>Phone:</strong> {record.get('phone') or '—'}</p>
      <p><strong>Monthly reports:</strong> {record.get('estimated_monthly_reports') or '—'}</p>
      <p><strong>Notes:</strong><br>{record.get('notes') or '—'}</p>
    """
    return notify_internal(subject, build_html(inner))
