import React from "react";
import { AlertTriangle, ShieldAlert, ShieldCheck, Lock, ArrowRight } from "lucide-react";

const PAYMENT_LINKS = {
  single: process.env.NEXT_PUBLIC_PAYMENT_LINK_SINGLE || "#",
  tenpack: process.env.NEXT_PUBLIC_PAYMENT_LINK_TENPACK || "#",
};

export default function LiveReport({ report }) {
  const summary = report?.summary || {};

  // LOCKED/TEASER STATE — show counts + payment CTA
  if (summary.locked) {
    return <TeaserReport summary={summary} />;
  }

  const prop = summary.property_identification || {};
  const scheme = summary.scheme_overview || {};
  const fin = summary.financial_position || {};
  const bylaws = summary.by_laws_summary || {};
  const items = Array.isArray(summary.items_for_buyer_to_discuss_with_their_conveyancer)
    ? summary.items_for_buyer_to_discuss_with_their_conveyancer : [];
  const defects = summary.building_condition_and_defects || {};
  const insurance = summary.insurance || {};
  const compliance = summary.compliance || {};
  const embedded = summary.embedded_network || {};
  const disputes = summary.disputes_and_legal_matters || {};
  const missing = Array.isArray(summary.items_unclear_or_missing_from_report)
    ? summary.items_unclear_or_missing_from_report : [];

  return (
    <div className="bg-white p-8 md:p-14 shadow-2xl" style={{ fontFamily: "'Inter', sans-serif" }}>
      {/* Header */}
      <div className="flex items-start justify-between border-b-2 border-ink pb-6 mb-8 flex-wrap gap-4">
        <div>
          <div className="mono text-[10px] uppercase tracking-widest text-ink/50">StrataSnap Summary</div>
          <h3 className="serif text-2xl md:text-3xl font-bold mt-1">
            {prop.address_as_stated || "Property address not stated in document"}
          </h3>
          <div className="text-sm text-ink/60 mt-1">
            {prop.strata_plan_number && <>Strata Plan {prop.strata_plan_number} · </>}
            {scheme.total_lots && <>{scheme.total_lots} lots · </>}
            {summary.document_type_detected && <>{summary.document_type_detected} · </>}
            Generated {new Date().toLocaleDateString("en-AU", { day: "numeric", month: "long", year: "numeric" })}
          </div>
        </div>
      </div>

      {/* Disclaimer */}
      <div className="border border-ink/20 bg-ink/[0.03] p-4 mb-8">
        <div className="text-xs text-ink/75 leading-relaxed">
          <span className="font-bold">Important. </span>
          This summary is generated by AI from the contents of the strata documents provided. It is not legal, financial, or property advice. It is not a formal strata inspection report.
          {summary.is_section_184_certificate && (
            <> Under s.185 of the SSM Act 2015, a s.184 certificate is conclusive evidence of the matters stated in it. Accuracy of extraction from this document type is especially important — verify key findings against the source.</>
          )}
        </div>
      </div>

      {/* Financial position */}
      {(fin.administrative_fund_balance?.amount || fin.capital_works_fund_balance?.amount) && (
        <Section tag="§ Financial position">
          <div className="grid md:grid-cols-3 gap-6 mb-6">
            {fin.administrative_fund_balance?.amount && (
              <Stat label="Administrative fund" value={fin.administrative_fund_balance.amount} sub={fin.administrative_fund_balance.as_at_date} />
            )}
            {fin.capital_works_fund_balance?.amount && (
              <Stat label="Capital works fund" value={fin.capital_works_fund_balance.amount} sub={fin.capital_works_fund_balance.as_at_date} />
            )}
            {fin.current_quarterly_levies?.administrative_fund_levy && (
              <Stat label="Quarterly levy" value={fin.current_quarterly_levies.administrative_fund_levy} sub="Per lot" />
            )}
          </div>
          {fin.ten_year_capital_works_fund_plan?.is_referenced && (
            <Finding tag="Capital works fund" refText="SSM Act s.74, s.80" page={fin.ten_year_capital_works_fund_plan.page_reference} title="10-year capital works fund plan" body={fin.ten_year_capital_works_fund_plan.explanation} />
          )}
          {fin.outstanding_arrears?.total_amount_owed_by_lot_owners && fin.outstanding_arrears.total_amount_owed_by_lot_owners !== "not_provided" && (
            <Finding tag="Arrears" refText="SSM Act s.85" page={fin.outstanding_arrears.page_reference} title={`Outstanding arrears: ${fin.outstanding_arrears.total_amount_owed_by_lot_owners}`} body={fin.outstanding_arrears.explanation || "Arrears are owed by lot owners to the owners corporation."} />
          )}
          {fin.outstanding_arrears?.arrears_for_subject_lot && fin.outstanding_arrears.arrears_for_subject_lot !== "not_provided" && (
            <Finding tag="Subject lot arrears" refText="SSM Act s.85" page={fin.outstanding_arrears.page_reference} title={`Arrears on this lot: ${fin.outstanding_arrears.arrears_for_subject_lot}`} body="Arrears outstanding on the specific lot being purchased." />
          )}
        </Section>
      )}

      {/* Compliance / Fire Safety */}
      {compliance && Object.keys(compliance).length > 0 && (
        <Section tag="§ Compliance and fire safety">
          {compliance.overall_risk_rating && (
            <div className="mb-6">
              <RiskBadge rating={compliance.overall_risk_rating} />
            </div>
          )}
          {compliance.annual_fire_safety_statement?.status && compliance.annual_fire_safety_statement.status !== "not_provided" && (
            <Finding
              tag="AFSS"
              refText="EP&A Regulation"
              page={compliance.annual_fire_safety_statement.page_reference}
              title={`Annual Fire Safety Statement: ${compliance.annual_fire_safety_statement.status}${compliance.annual_fire_safety_statement.months_overdue ? ` (${compliance.annual_fire_safety_statement.months_overdue} months overdue)` : ""}`}
              body={compliance.annual_fire_safety_statement.explanation}
              severity={compliance.annual_fire_safety_statement.status === "overdue" ? "critical" : "clear"}
            />
          )}
          {compliance.building_defect_orders?.has_outstanding_orders === true && Array.isArray(compliance.building_defect_orders.orders) && (
            compliance.building_defect_orders.orders.map((order, i) => (
              <Finding key={i} tag="Outstanding order" refText="s.184 item 12A" page={order.page_reference} title={`${order.order_type}: ${order.description}`} body={`Issued by: ${order.issuing_body || "not stated"}`} severity="critical" />
            ))
          )}
          {compliance.building_defect_orders?.has_outstanding_orders === false && (
            <Finding tag="Outstanding orders" refText="s.184 item 12A" title="No outstanding orders noted" body="No rectification orders, cladding orders, or development control orders are recorded." severity="clear" />
          )}
          {compliance.cladding?.status && compliance.cladding.status !== "not_provided" && compliance.cladding.status !== "none_noted" && (
            <Finding tag="Cladding" page={compliance.cladding.page_reference} title={`Combustible cladding: ${compliance.cladding.status}`} body={compliance.cladding.explanation || compliance.cladding.details} severity={compliance.cladding.status === "under_order" || compliance.cladding.status === "identified" ? "critical" : "attention"} />
          )}
          {compliance.fire_safety_measures?.status === "deficiencies_noted" && (
            <Finding tag="Fire safety measures" page={compliance.fire_safety_measures.page_reference} title="Fire safety deficiencies noted" body={compliance.fire_safety_measures.deficiencies} severity="attention" />
          )}
          {compliance.asbestos?.status && compliance.asbestos.status !== "not_provided" && (
            <Finding tag="Asbestos" page={compliance.asbestos.page_reference} title={`Asbestos: ${compliance.asbestos.status.replace(/_/g, " ")}`} body={compliance.asbestos.explanation} severity={compliance.asbestos.status === "present_no_register" ? "attention" : "clear"} />
          )}
          {compliance.anchor_points_height_safety?.status && compliance.anchor_points_height_safety.status !== "not_provided" && (
            <Finding tag="Anchor points" page={compliance.anchor_points_height_safety.page_reference} title={`Height safety: ${compliance.anchor_points_height_safety.status}`} body={compliance.anchor_points_height_safety.certification_date ? `Last certified: ${compliance.anchor_points_height_safety.certification_date}` : ""} severity={compliance.anchor_points_height_safety.status === "expired" ? "attention" : "clear"} />
          )}
          {compliance.whs?.status && compliance.whs.status !== "not_provided" && compliance.whs.status !== "not_applicable" && (
            <Finding tag="WHS" page={compliance.whs.page_reference} title={`Work health and safety: ${compliance.whs.status}`} body={compliance.whs.note} />
          )}
          {compliance.window_safety_devices?.status && compliance.window_safety_devices.status !== "not_provided" && (
            <Finding tag="Window safety" refText="SSM Act s.118" page={compliance.window_safety_devices.page_reference} title={`Window safety devices: ${compliance.window_safety_devices.status}`} body={compliance.window_safety_devices.explanation} />
          )}
          {compliance.missing_information && compliance.missing_information !== "not_provided" && (
            <div className="border-l-2 border-gold pl-5 py-3 mb-4 bg-gold/5">
              <div className="mono text-[10px] uppercase tracking-widest text-ink/50 mb-2">Missing compliance information</div>
              <p className="text-sm text-ink/75 leading-relaxed">{compliance.missing_information}</p>
            </div>
          )}
        </Section>
      )}

      {/* Building defects */}
      {Array.isArray(defects.defects_identified_in_report) && defects.defects_identified_in_report.length > 0 && (
        <Section tag="§ Building condition and defects">
          {defects.defects_identified_in_report.map((d, i) => (
            <Finding
              key={i}
              tag={d.severity_as_stated || "Defect noted"}
              refText="SSM Act s.106"
              page={d.page_reference}
              title={d.issue || "Defect identified"}
              body={`${d.location && d.location !== "not stated" ? `Location: ${d.location}. ` : ""}${d.context || ""}`}
            />
          ))}
        </Section>
      )}

      {/* By-laws */}
      {Array.isArray(bylaws.notable_by_laws) && bylaws.notable_by_laws.length > 0 && (
        <Section tag="§ Notable by-laws">
          {bylaws.notable_by_laws.map((bl, i) => (
            <Finding
              key={i}
              tag={`By-law ${bl.by_law_number || "—"} — ${bl.topic || "general"}`}
              refText={bl.statutory_reference}
              page={bl.page_reference}
              title={bl.topic || "By-law noted"}
              body={bl.what_it_says || "Details not extracted."}
            />
          ))}
        </Section>
      )}

      {/* Insurance */}
      {insurance.building_replacement_value && insurance.building_replacement_value !== "not_provided" && (
        <Section tag="§ Insurance">
          <Finding
            tag="Damage policy"
            refText="SSM Act s.160, s.161, s.164"
            page={insurance.page_reference}
            title={`Building insured for ${insurance.building_replacement_value}`}
            body={insurance.explanation}
          />
        </Section>
      )}

      {/* Embedded network */}
      {embedded.has_embedded_network === true && (
        <Section tag="§ Embedded network">
          <Finding
            tag="Exclusive supply"
            page={embedded.page_reference}
            title="This scheme has an embedded electricity network"
            body={embedded.explanation || embedded.details || "An embedded network may limit the buyer's choice of electricity retailer after purchase."}
            severity="attention"
          />
        </Section>
      )}

      {/* Disputes */}
      {Array.isArray(disputes.ncat_proceedings_referenced) && disputes.ncat_proceedings_referenced.length > 0 && (
        <Section tag="§ Disputes and legal matters">
          {disputes.ncat_proceedings_referenced.map((d, i) => (
            <Finding key={i} tag="NCAT proceedings" page={d.page_reference} title={d.description || d.issue || "Proceedings noted"} body={d.context || d.details || ""} />
          ))}
          {disputes.legal_costs_in_financials && disputes.legal_costs_in_financials !== "not_provided" && (
            <Finding tag="Legal costs" title={`Legal costs in financials: ${disputes.legal_costs_in_financials}`} body={disputes.explanation} />
          )}
        </Section>
      )}

      {/* Items to discuss */}
      {items.length > 0 && (
        <Section tag="§ Items to discuss with your conveyancer">
          <ul className="text-sm text-ink/85 space-y-3 leading-relaxed">
            {items.map((item, i) => (
              <li key={i} className="flex gap-3">
                <span className="text-red font-bold shrink-0">→</span>
                <span>{typeof item === "string" ? item : item.description || item.item || JSON.stringify(item)}</span>
              </li>
            ))}
          </ul>
        </Section>
      )}

      {/* Items missing from report */}
      {missing.length > 0 && (
        <Section tag="§ Information unclear or missing from this document">
          <ul className="text-sm text-ink/85 space-y-3 leading-relaxed">
            {missing.map((item, i) => (
              <li key={i} className="flex gap-3">
                <span className="text-gold font-bold shrink-0">?</span>
                <span>{typeof item === "string" ? item : item.description || JSON.stringify(item)}</span>
              </li>
            ))}
          </ul>
        </Section>
      )}

      {/* Footer */}
      <div className="border-t border-ink/15 mt-10 pt-6 flex items-center justify-between flex-wrap gap-4">
        <div className="mono text-[10px] uppercase tracking-widest text-ink/40">
          AI-generated · Information only · Not legal, financial, or property advice
        </div>
        <div className="serif text-sm font-bold">— StrataSnap</div>
      </div>
    </div>
  );
}


// ─── TEASER REPORT (locked/unpaid) ─────────────────────────────────

function TeaserReport({ summary }) {
  const prop = summary.property_identification || {};
  const scheme = summary.scheme_overview || {};
  const fin = summary.financial_position || {};
  const counts = summary.finding_counts || {};

  return (
    <div className="bg-white p-8 md:p-14 shadow-2xl relative" style={{ fontFamily: "'Inter', sans-serif" }}>
      {/* Header */}
      <div className="flex items-start justify-between border-b-2 border-ink pb-6 mb-8 flex-wrap gap-4">
        <div>
          <div className="mono text-[10px] uppercase tracking-widest text-ink/50">StrataSnap Summary — Preview</div>
          <h3 className="serif text-2xl md:text-3xl font-bold mt-1">
            {prop.address_as_stated || "Property address not stated"}
          </h3>
          <div className="text-sm text-ink/60 mt-1">
            {prop.strata_plan_number && <>Strata Plan {prop.strata_plan_number} · </>}
            {scheme.total_lots && <>{scheme.total_lots} lots</>}
          </div>
        </div>
      </div>

      {/* Visible: fund balances */}
      {(fin.administrative_fund_balance?.amount || fin.capital_works_fund_balance?.amount) && (
        <div className="mb-8">
          <div className="mono text-[10px] uppercase tracking-widest text-red mb-3">§ Financial position</div>
          <div className="grid md:grid-cols-2 gap-6">
            {fin.administrative_fund_balance?.amount && (
              <Stat label="Administrative fund" value={fin.administrative_fund_balance.amount} sub={fin.administrative_fund_balance.as_at_date} />
            )}
            {fin.capital_works_fund_balance?.amount && (
              <Stat label="Capital works fund" value={fin.capital_works_fund_balance.amount} sub={fin.capital_works_fund_balance.as_at_date} />
            )}
          </div>
        </div>
      )}

      {/* Finding counts — locked */}
      <div className="border-2 border-ink/20 bg-ink/[0.02] p-8 mb-8">
        <div className="flex items-center gap-3 mb-6">
          <Lock size={20} className="text-red" />
          <div className="serif text-xl font-bold">We found {(counts.defects_flagged || 0) + (counts.notable_by_laws || 0) + (counts.items_for_conveyancer || 0) + (counts.disputes_or_proceedings || 0)} items in this document.</div>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-3 gap-4 mb-6">
          {counts.defects_flagged > 0 && <CountTile label="Defects flagged" count={counts.defects_flagged} />}
          {counts.notable_by_laws > 0 && <CountTile label="Notable by-laws" count={counts.notable_by_laws} />}
          {counts.items_for_conveyancer > 0 && <CountTile label="Items for your conveyancer" count={counts.items_for_conveyancer} />}
          {counts.disputes_or_proceedings > 0 && <CountTile label="Disputes / proceedings" count={counts.disputes_or_proceedings} />}
          {counts.items_unclear_or_missing > 0 && <CountTile label="Missing information" count={counts.items_unclear_or_missing} />}
          {counts.compliance_risk_rating && <CountTile label="Compliance" count={counts.compliance_risk_rating} isText />}
        </div>
        {counts.has_outstanding_orders && (
          <div className="flex items-center gap-2 text-sm text-red font-bold mb-4">
            <AlertTriangle size={16} /> Outstanding orders detected — unlock to see details.
          </div>
        )}
        <div className="flex flex-wrap items-center gap-4">
          <a href={PAYMENT_LINKS.single} target="_blank" rel="noopener noreferrer" className="bg-ink text-cream px-8 py-4 font-medium hover:bg-red transition-colors flex items-center gap-2">
            Unlock full summary — $14.99 <ArrowRight size={18} />
          </a>
          <a href={PAYMENT_LINKS.tenpack} target="_blank" rel="noopener noreferrer" className="text-sm underline underline-offset-4 hover:text-red">
            Or get 10 reports for $74.99
          </a>
        </div>
      </div>

      <div className="border-t border-ink/15 pt-6 mono text-[10px] uppercase tracking-widest text-ink/40">
        AI-generated · Information only · Not legal, financial, or property advice
      </div>
    </div>
  );
}


// ─── SHARED COMPONENTS ─────────────────────────────────────

function Section({ tag, children }) {
  return (
    <div className="mb-10">
      <div className="mono text-[10px] uppercase tracking-widest text-red mb-3">{tag}</div>
      {children}
    </div>
  );
}

function Finding({ tag, refText, page, title, body, severity }) {
  const borderColor = severity === "critical" ? "border-red" : severity === "attention" ? "border-gold" : "border-ink/40";
  const bgColor = severity === "critical" ? "bg-red/5" : severity === "attention" ? "bg-gold/5" : "";
  return (
    <div className={`border-l-2 ${borderColor} ${bgColor} pl-5 py-3 mb-4`}>
      <div className="flex flex-wrap items-center gap-3 mb-2">
        <div className="mono text-[10px] uppercase tracking-widest text-red">{tag}</div>
        {severity === "critical" && <span className="mono text-[10px] uppercase tracking-widest text-red bg-red/10 px-2 py-0.5">Critical</span>}
        {severity === "attention" && <span className="mono text-[10px] uppercase tracking-widest text-gold bg-gold/10 px-2 py-0.5">Attention</span>}
        {refText && <div className="mono text-[10px] uppercase tracking-widest text-ink/50">{refText}</div>}
        {page && <div className="mono text-[10px] uppercase tracking-widest text-ink/50">{page}</div>}
      </div>
      <div className="serif text-lg font-bold leading-snug">{title}</div>
      {body && <p className="text-sm text-ink/75 mt-2 leading-relaxed">{body}</p>}
    </div>
  );
}

function Stat({ label, value, sub }) {
  return (
    <div className="border border-ink/15 p-5">
      <div className="mono text-[10px] uppercase tracking-widest text-ink/50 mb-2">{label}</div>
      <div className="serif text-2xl md:text-3xl font-bold text-ink">{value}</div>
      {sub && <div className="text-xs text-ink/60 mt-1">{sub}</div>}
    </div>
  );
}

function RiskBadge({ rating }) {
  const config = {
    critical: { icon: ShieldAlert, color: "text-red", bg: "bg-red/10", label: "Critical items found" },
    attention: { icon: AlertTriangle, color: "text-gold", bg: "bg-gold/10", label: "Items need attention" },
    clear: { icon: ShieldCheck, color: "text-green-700", bg: "bg-green-50", label: "No critical compliance issues" },
  };
  const c = config[rating] || config.clear;
  const Icon = c.icon;
  return (
    <div className={`${c.bg} border border-current/10 px-4 py-3 flex items-center gap-3 ${c.color}`}>
      <Icon size={20} />
      <div className="mono text-xs uppercase tracking-widest">{c.label}</div>
    </div>
  );
}

function CountTile({ label, count, isText }) {
  return (
    <div className="border border-ink/15 p-4 text-center">
      <div className={`serif font-bold ${isText ? "text-xl" : "text-3xl"} text-ink`}>{count}</div>
      <div className="mono text-[10px] uppercase tracking-widest text-ink/50 mt-1">{label}</div>
    </div>
  );
}
