import React from "react";
import { ShieldAlert } from "lucide-react";

export default function SampleReport({ light = false }) {
  const bg = light ? "bg-cream text-ink" : "bg-white text-ink";
  return (
    <div className={`${bg} p-8 md:p-14 shadow-2xl`} style={{ fontFamily: "'Inter', sans-serif" }}>
      {/* Header */}
      <div className="flex items-start justify-between border-b-2 border-ink pb-6 mb-8 flex-wrap gap-4">
        <div>
          <div className="mono text-[10px] uppercase tracking-widest text-ink/50">StrataSnap Summary</div>
          <h3 className="serif text-2xl md:text-3xl font-bold mt-1">12/47 Bondi Road, Bondi NSW 2026</h3>
          <div className="text-sm text-ink/60 mt-1">Strata Plan 78421 · 32 lots · Strata inspection report · Generated 18 July 2026</div>
        </div>
        <div className="text-right">
          <div className="mono text-[10px] uppercase tracking-widest text-ink/50">Source</div>
          <div className="text-sm font-medium mt-1">Strata report (216pp)</div>
          <div className="text-xs text-ink/60">Prepared by Strata Inspections Co. · 14 April 2026</div>
        </div>
      </div>

      {/* Disclaimer */}
      <div className="border border-ink/20 bg-ink/[0.03] p-4 mb-8">
        <div className="text-xs text-ink/75 leading-relaxed">
          <span className="font-bold">Important. </span>
          This summary is generated by AI from the contents of the strata documents provided. It is not legal, financial, or property advice. It is not a formal strata inspection report. Before making any property purchase decision, obtain professional advice from a qualified conveyancer or solicitor.
        </div>
      </div>

      {/* Financial position */}
      <div className="mb-10">
        <div className="mono text-[10px] uppercase tracking-widest text-red mb-3">§ Financial position</div>
        <div className="grid md:grid-cols-3 gap-6 mb-6">
          <Stat label="Administrative fund" value="$48,200" sub="As at 31 Mar 2026" />
          <Stat label="Capital works fund" value="$112,500" sub="As at 31 Mar 2026" />
          <Stat label="Quarterly levy (admin + cap)" value="$1,420 + $980" sub="Per lot" />
        </div>
        <Finding tag="Capital works fund" refText="SSM Act s.74, s.80" page="pp. 84, 91"
          title="Capital works fund balance is $112,500 against a 10-year forecast spend of $1.2M"
          body="The administrative fund covers day-to-day expenses (SSM Act s.73). The capital works fund covers long-term major repairs such as roof, lifts, and external painting (SSM Act s.74). Owners corporations must prepare a 10-year capital works fund plan (SSM Act s.80). The plan in this report (p.84) forecasts $1.2M in major works including roof replacement scheduled for 2027 and lift overhaul scheduled for 2028. The current balance of $112,500 represents approximately 9% of the 10-year forecast spend stated in the plan."
        />
        <Finding tag="Special levies" refText="SSM Act s.81(4)" page="pp. 198, 201"
          title="A special levy of $4,800 per lot is due September 2026"
          body="The owners corporation resolved at the EGM on 12 March 2026 (p.198) to raise a special levy of $4,800 per lot to fund external rendering works. The levy is payable on 30 September 2026. Special levies for specific expenditure are authorised under SSM Act s.81(4). If contracts exchange before settlement of this levy, the apportionment of this amount is a matter to discuss with your conveyancer."
        />
        <Finding tag="Arrears" refText="SSM Act s.85" page="p. 96"
          title="Outstanding arrears of $2,740 across four lots"
          body="The financial statements (p.96) show $2,740 in outstanding levy arrears across four lots. The subject lot (lot 12) shows no arrears. Levy arrears are recoverable by the owners corporation under SSM Act s.85, including interest."
        />
      </div>

      {/* Compliance / Fire Safety */}
      <div className="mb-10">
        <div className="mono text-[10px] uppercase tracking-widest text-red mb-3">§ Compliance and fire safety</div>
        <div className="mb-6">
          <div className="bg-gold/10 border border-gold/30 px-4 py-3 flex items-center gap-3 text-gold">
            <ShieldAlert size={20} />
            <div className="mono text-xs uppercase tracking-widest">Items need attention</div>
          </div>
        </div>
        <Finding tag="AFSS" refText="EP&A Regulation" page="p. 172"
          title="Annual Fire Safety Statement: current"
          body="The AFSS was lodged with council on 14 January 2026 (p.172). Next due January 2027. The AFSS is current."
          severity="clear"
        />
        <Finding tag="Cladding" page="pp. 155-158"
          title="Combustible cladding: rectification works completed 2024"
          body="The building was identified on the NSW Cladding Register in 2020 (p.155). Aluminium composite panel (ACP) cladding on levels 3-8 was replaced with non-combustible panels. Rectification completed November 2024 and signed off by a fire engineer (p.158)."
          severity="clear"
        />
        <Finding tag="Asbestos" page="p. 164"
          title="Asbestos: present and managed"
          body="An asbestos register is in place (p.164). Asbestos-containing materials are recorded in common area pipe lagging and eaves lining. An asbestos management plan is current. This is expected in buildings of this age (constructed pre-1990) and is not alarming when a register and management plan are in place."
          severity="clear"
        />
        <div className="border-l-2 border-gold pl-5 py-3 mb-4 bg-gold/5">
          <div className="mono text-[10px] uppercase tracking-widest text-ink/50 mb-2">Missing compliance information</div>
          <p className="text-sm text-ink/75 leading-relaxed">The document does not address anchor point / height safety certification or WHS compliance status.</p>
        </div>
      </div>

      {/* Building defects */}
      <div className="mb-10">
        <div className="mono text-[10px] uppercase tracking-widest text-red mb-3">§ Building condition and defects</div>
        <Finding tag="Active proceedings" refText="SSM Act s.106, Part 11" page="pp. 147–152"
          title="A waterproofing claim is currently before NCAT, hearing scheduled for August 2026"
          body="The owners corporation lodged a defect claim relating to water ingress in lots 4, 9, and 14 in March 2024 (p.147). The matter is listed for hearing in August 2026. Owners corporations have a duty to maintain and repair common property under SSM Act s.106. Building defect claims for buildings completed in the past 6 years may be supported by the building bond regime under SSM Act Part 11. The report does not specify whether a building bond was issued for this scheme."
        />
      </div>

      {/* By-laws — CORRECTED */}
      <div className="mb-10">
        <div className="mono text-[10px] uppercase tracking-widest text-red mb-3">§ Notable by-laws</div>
        <Finding tag="By-law 14 — Pets" refText="SSM Act s.137B, s.139" page="p. 73"
          title="By-law 14 requires written approval from the owners corporation to keep an animal"
          body="By-law 14 (p.73) states that no animal may be kept on a lot or common property without the written approval of the owners corporation. Recent committee minutes (p.209) record two refusals of pet applications in 2025. Under SSM Act s.137B, a by-law must not unreasonably prohibit the keeping of an animal on a lot. Whether a consent-based by-law amounts to unreasonable prohibition depends on how the consent process operates in practice. This is a matter to discuss with your conveyancer if pets are a consideration for your purchase."
        />
        <Finding tag="By-law 22 — Short-term letting" refText="SSM Act s.137A" page="p. 81"
          title="By-law 22 restricts short-term rental accommodation to a minimum 90-day stay"
          body="By-law 22 (p.81) restricts the letting of any lot for a continuous period of less than 90 days. SSM Act s.137A permits by-laws restricting short-term rental accommodation in certain circumstances. However, an owner who uses the lot as their principal place of residence may let it short-term subject to day caps, regardless of this by-law. If you intend to use the property for short-term letting (Airbnb, holiday rental), discuss the interaction between this by-law and the s.137A principal-place-of-residence carve-out with your conveyancer."
        />
      </div>

      {/* Insurance */}
      <div className="mb-10">
        <div className="mono text-[10px] uppercase tracking-widest text-red mb-3">§ Insurance</div>
        <Finding tag="Damage policy" refText="SSM Act s.160, s.161, s.164" page="p. 188"
          title="Building insurance is current with $24M sum insured and $20M public liability"
          body="Owners corporations must insure the building under SSM Act s.160. The current policy with CHU Underwriting (p.188) was renewed on 1 February 2026 with a sum insured of $24M for damage and $20M for public liability. Public liability cover meets the regulatory minimum of $20M (SSM Regulation 2016 cl.40). No claims are recorded against the policy in the current term."
        />
      </div>

      {/* Items to discuss */}
      <div className="mb-6">
        <div className="mono text-[10px] uppercase tracking-widest text-red mb-3">§ Items to discuss with your conveyancer</div>
        <ul className="text-sm text-ink/85 space-y-3 leading-relaxed">
          <li className="flex gap-3"><span className="text-red font-bold">→</span><span>The capital works fund balance of $112,500 represents approximately 9% of the 10-year forecast spend of $1.2M (p.84). What does your conveyancer make of this?</span></li>
          <li className="flex gap-3"><span className="text-red font-bold">→</span><span>A special levy of $4,800 per lot is due 30 September 2026 (p.198). If contracts exchange before then, how should this be apportioned?</span></li>
          <li className="flex gap-3"><span className="text-red font-bold">→</span><span>The waterproofing claim listed for hearing in August 2026 (p.147) — what is the potential impact on lot owners if the claim is unsuccessful?</span></li>
          <li className="flex gap-3"><span className="text-red font-bold">→</span><span>By-law 14 (pets) — if pets matter to you, does your conveyancer consider the consent requirement to amount to an unreasonable prohibition under SSM Act s.137B?</span></li>
          <li className="flex gap-3"><span className="text-red font-bold">→</span><span>By-law 22 (short-term letting) — if you intend to let short-term, does the s.137A principal-place-of-residence carve-out apply to your situation?</span></li>
          <li className="flex gap-3"><span className="text-red font-bold">→</span><span>The document does not address anchor point certification or WHS compliance — should these be checked separately?</span></li>
        </ul>
      </div>

      {/* Footer */}
      <div className="border-t border-ink/15 mt-10 pt-6 flex items-center justify-between">
        <div className="mono text-[10px] uppercase tracking-widest text-ink/40">AI-generated · Information only · Not legal, financial, or property advice</div>
        <div className="serif text-sm font-bold">— StrataSnap</div>
      </div>
    </div>
  );
}

function Finding({ tag, refText, page, title, body, severity }) {
  const borderColor = severity === "critical" ? "border-red" : severity === "attention" ? "border-gold" : "border-ink/40";
  const bgColor = severity === "critical" ? "bg-red/5" : severity === "attention" ? "bg-gold/5" : "";
  return (
    <div className={`border-l-2 ${borderColor} ${bgColor} pl-5 py-3 mb-4`}>
      <div className="flex flex-wrap items-center gap-3 mb-2">
        <div className="mono text-[10px] uppercase tracking-widest text-red">{tag}</div>
        {severity === "critical" && <span className="mono text-[10px] uppercase tracking-widest text-red bg-red/10 px-2 py-0.5">Critical</span>}
        {severity === "attention" && <span className="mono text-[10px] uppercase tracking-widest text-gold bg-gold/10 px-2 py-0.5">Attention</span>}
        {refText && <div className="mono text-[10px] uppercase tracking-widest text-ink/50">{refText}</div>}
        {page && <div className="mono text-[10px] uppercase tracking-widest text-ink/50">{page}</div>}
      </div>
      <div className="serif text-lg font-bold leading-snug">{title}</div>
      {body && <p className="text-sm text-ink/75 mt-2 leading-relaxed">{body}</p>}
    </div>
  );
}

function Stat({ label, value, sub }) {
  return (
    <div className="border border-ink/15 p-5">
      <div className="mono text-[10px] uppercase tracking-widest text-ink/50 mb-2">{label}</div>
      <div className="serif text-2xl md:text-3xl font-bold text-ink">{value}</div>
      {sub && <div className="text-xs text-ink/60 mt-1">{sub}</div>}
    </div>
  );
}
